### ISSUE TITLE
Dateiformate

### ISSUE THREAD

**Issue by Paloox** [Runinho/MusikMacher#1]
Wenn man eine mp3 datei hat und die endung der datei zum Beispiel so aussiehr: soundDatei.MP3 dann funktioniert das importieren nicht, wenn sie aber so ist: soundDatei.mp3 dann schon

**Comment by Runinho** [comment]
Hi,

Ist in Version 0.1.15 gefixt.

Hier ist die Stelle im Code 😄:
https://github.com/Runinho/MusikMacher/commit/c72eadd572ab6f25cab743b5a4ab6166bc64a9b1#diff-f601e8833bc900fa0d01371d6179c1a8b23f00ff6bd1d63f99a206dc738bf84fR133
