### ISSUE TITLE
Bekomme nur eine Windows Fehlermeldung wenn ich ein Song suchen möchte

### ISSUE THREAD

**Issue by Dotta4You** [Runinho/MusikMacher#3]
Hey,

Immer wenn ich ein Song suchen möchte, bekomme ich nur folgenden Fehler:
Neu Download hat nichts gebracht, es werden auch keinerlei songs auf der Startseite angezeigt*

![image](https://github.com/user-attachments/assets/f85c257d-347a-4ff0-9abe-e139ea23726f)

**Comment by Runinho** [comment]
Hi,

Danke für den Bug Report.
Jo, der Code funktioniert nicht, wenn keine Songs geladen sind 😆 

Fehler ist in dieser Zeile: https://github.com/Runinho/MusikMacher/blob/7848a8820a335fd92b79035f73d60f78f290d7b1/MusikMacher/components/Browse.xaml.cs#L74

Glaube das Hauptproblem ist eher, dass du keine Songs reingeladen hast. Bist du dir sicher, dass der Pfad, den du angegeben hast, korrekt ist?
Dir sollte nach dem Import auch angezeigt werden, wie viele Songs reingeladen wurden :)

**Comment by Dotta4You** [comment]
Hey, ja der pfad ist korrekt, sollte eigentlich alles funktionieren^^

**Comment by Runinho** [comment]
habe den crash in der version Alpha v0.1.20 gefixt.

Funktioniert es jetzt wie du es erwartest?

**Comment by Dotta4You** [comment]
Ja perfekt klappt jz für mich^^
