### ISSUE TITLE
Featureanfrage: Back Button für Random-Auswahl

### ISSUE THREAD

**Issue by SweeD** [Runinho/MusikMacher#5]
Beschreibung von Loru:
https://www.twitch.tv/itsloru/clip/DifficultSquareStinkbugPanicBasket-GUMOQbXfvPO_N-qs

Bin nur der Überbringer. 🤣

**Comment by Runinho** [comment]
Danke fürs weiter geben :)

added in [Alpha v0.1.20](https://github.com/Runinho/MusikMacher/releases/tag/v0.1.20-alpha)
